version: '3'
services:
 config:
  image: karolwojtas/conhubconfigserver
  ports:
  - "8888:8888"
  networks:
  - my-net
  expose:
  - 8888
  environment:
   EUREKA_SERVER_HOST: eureka
 eureka:
  image: karolwojtas/conhubeurekaserver
  ports:
  - "8080:8761"
  networks:
  - my-net
  expose:
  - 8761
  depends_on:
  - config
  environment:
   CONFIG_SERVER_HOST: config
 gateway:
  image: karolwojtas/conhubgateway
  ports:
  - "8765:8765"
  environment:
   EUREKA_SERVER_HOST: eureka
   CONFIG_SERVER_HOST: config
  networks:
  - my-net
  depends_on:
  - eureka
  - config
  expose:
  - 8765
networks:
 my-net:
  driver: overlay